// §5.1: "At build time, generate src/design/fonts.generated.ts from whatever is
// actually in that folder: family name, file path, weight, style. If I add a font
// file and rebuild, it must appear in the app without anyone editing code by hand."
//
// Metadata is read from each file's own sfnt tables, never from its filename.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { join, extname } from 'node:path';

const SRC = 'assets/fonts';
const PUBLIC = 'public/fonts';
const FACE_EXT = new Set(['.ttf', '.otf', '.woff2', '.woff']);

function sfntTables(buf) {
  const count = buf.readUInt16BE(4);
  const t = {};
  for (let i = 0; i < count; i++) {
    const o = 12 + i * 16;
    t[buf.toString('latin1', o, o + 4)] = { off: buf.readUInt32BE(o + 8), len: buf.readUInt32BE(o + 12) };
  }
  return t;
}

function readNames(buf, t) {
  if (!t.name) return {};
  const { off } = t.name;
  const count = buf.readUInt16BE(off + 2);
  const strOff = buf.readUInt16BE(off + 4);
  const out = {};
  for (let i = 0; i < count; i++) {
    const o = off + 6 + i * 12;
    const platform = buf.readUInt16BE(o);
    const nameId = buf.readUInt16BE(o + 6);
    const len = buf.readUInt16BE(o + 8);
    const so = buf.readUInt16BE(o + 10);
    const raw = buf.subarray(off + strOff + so, off + strOff + so + len);
    const s = platform === 3 ? raw.swap16().toString('utf16le') : raw.toString('latin1');
    if (out[nameId] === undefined) out[nameId] = s;
  }
  return out;
}

function describe(file) {
  const buf = readFileSync(join(SRC, file));
  const t = sfntTables(buf);
  const n = readNames(buf, t);
  const os2 = t['OS/2']?.off;
  const head = t.head?.off;
  const weight = os2 !== undefined ? buf.readUInt16BE(os2 + 4) : 400;
  const fsSelection = os2 !== undefined ? buf.readUInt16BE(os2 + 62) : 0;
  const macStyle = head !== undefined ? buf.readUInt16BE(head + 44) : 0;
  const italic = Boolean((macStyle & 0x2) || (fsSelection & 0x1));
  // OS/2 ulUnicodeRange1 bit 13 = Arabic. §5.3 disables the letter-spacing
  // slider for any Arabic face, so the picker needs this.
  const range1 = os2 !== undefined ? buf.readUInt32BE(os2 + 42) : 0;
  const arabic = Boolean(range1 & (1 << 13));
  return {
    family: n[16] || n[1] || file,
    style: n[17] || n[2] || 'Regular',
    weight,
    italic,
    arabic,
    file,
    src: `/fonts/${file}`,
  };
}

const files = readdirSync(SRC).filter(f => FACE_EXT.has(extname(f).toLowerCase())).sort();
if (files.length === 0) {
  console.error(`${SRC} contains no font files - see Claude.md Appendix.`);
  process.exit(1);
}
const faces = files.map(describe);

rmSync(PUBLIC, { recursive: true, force: true });
mkdirSync(PUBLIC, { recursive: true });
for (const f of files) copyFileSync(join(SRC, f), join(PUBLIC, f));

const fmt = f => ({ '.ttf': 'truetype', '.otf': 'opentype', '.woff2': 'woff2', '.woff': 'woff' }[extname(f).toLowerCase()]);

// @font-face rules. §5.1: registered locally, never from a CDN and never assumed
// to exist on the system.
writeFileSync('src/design/fonts.generated.css',
  `/* GENERATED by scripts/generate-fonts.mjs - do not edit. */\n` +
  faces.map(f => `@font-face {
  font-family: '${f.family}';
  src: url('${f.src}') format('${fmt(f.file)}');
  font-weight: ${f.weight};
  font-style: ${f.italic ? 'italic' : 'normal'};
  font-display: block;
}`).join('\n') + '\n');

const families = [...new Set(faces.map(f => f.family))].map(name => ({
  name,
  arabic: faces.some(f => f.family === name && f.arabic),
  weights: [...new Set(faces.filter(f => f.family === name).map(f => f.weight))].sort((a, b) => a - b),
}));

writeFileSync('src/design/fonts.generated.ts',
  `// GENERATED by scripts/generate-fonts.mjs - do not edit.\n` +
  `export type BundledFace = {\n  family: string; style: string; weight: number;\n` +
  `  italic: boolean; arabic: boolean; file: string; src: string;\n};\n\n` +
  `export const BUNDLED_FACES: BundledFace[] = ${JSON.stringify(faces, null, 2)};\n\n` +
  `/** Families for the §5.2 picker. \`arabic\` gates the letter-spacing slider (§5.3). */\n` +
  `export const BUNDLED_FAMILIES = ${JSON.stringify(families, null, 2)} as const;\n`);

console.log(`fonts: ${faces.length} faces, ${families.length} families ->`,
  families.map(f => `${f.name} [${f.weights.join(',')}]${f.arabic ? ' ar' : ''}`).join(' | '));
